# Generated by Django 3.2.4 on 2021-07-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='post',
            name='image1_caption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image1_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2_caption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image2_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3_caption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image3_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4_caption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image4_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
